# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
# boxes at https://atlas.hashicorp.com/search.
Vagrant.configure(2) do |config|

  config.vm.define "ubuntu-trusty64" do |node|
    vconfig = YAML::load_file("./vagrant.ubuntu-trusty64.yml")

    node.vm.box = "ubuntu/trusty64"
    node.vm.box_download_insecure = true
    node.vm.boot_timeout = 9000
    node.vm.hostname = vconfig['vm']['hostname']
      
    node.ssh.username = vconfig['ssh']['username']
    node.ssh.password = vconfig['ssh']['password']
  
    node.vm.network "private_network", ip: vconfig['vm']['network']['ip']
    node.vm.network "public_network"

    node.vm.synced_folder vconfig['synced_folder']['config'], "/home/vagrant/config"
    node.vm.synced_folder vconfig['synced_folder']['provision'], "/home/vagrant/provision"
    node.vm.synced_folder vconfig['synced_folder']['installers'], "/home/vagrant/installers"
    node.vm.synced_folder vconfig['synced_folder']['shared'], "/home/vagrant/shared"

    node.vm.provider "virtualbox" do |vb|
  	  vb.gui = false
      vb.name = vconfig['vm']['vb']['name']
	  vb.memory = vconfig['vm']['vb']['memory']
    end
  
    node.vm.provision :shell, path: "./ubuntu-trusty64/provision/bootstrap.sh", args: "2>&1 | tee ./ubuntu-trusty64/shared/bootstrap.log"
  end

  config.vm.define "centos7" do |node|
    vconfig = YAML::load_file("./vagrant.centos7.yml")

    node.vm.box = "temikus/centos-7.0-vbox-puppet"
    node.vm.box_download_insecure = true
    node.vm.boot_timeout = 9000
    node.vm.hostname = vconfig['vm']['hostname']
      
    node.ssh.username = vconfig['ssh']['username']
    node.ssh.password = vconfig['ssh']['password']
  
    node.vm.network "private_network", ip: vconfig['vm']['network']['ip']
    node.vm.network "public_network"

    node.vm.synced_folder vconfig['synced_folder']['config'], "/home/vagrant/config"
    node.vm.synced_folder vconfig['synced_folder']['provision'], "/home/vagrant/provision"
    node.vm.synced_folder vconfig['synced_folder']['installers'], "/home/vagrant/installers"
    node.vm.synced_folder vconfig['synced_folder']['shared'], "/home/vagrant/shared"

    node.vm.provider "virtualbox" do |vb|
  	  vb.gui = false
      vb.name = vconfig['vm']['vb']['name']
	  vb.memory = vconfig['vm']['vb']['memory']
    end
  
    node.vm.provision :shell, path: "./centos7/provision/bootstrap.sh", args: "2>&1 | tee ./centos7/shared/bootstrap.log"
  end
end
